// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrufhuhajvsrfhtloiym.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxydWZodWhhanZzcmZodGxvaXltIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI4ODA0NTYsImV4cCI6MjA1ODQ1NjQ1Nn0.cr6ovMkKjLMXRHHe5CJEYFB-Q7zhyuw0_XqoA6hg9QU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);